### PR TITLE
Yada, yada, pull request, second attempt...

### PR DESCRIPTION
**Pull request by rhq-migration-test-user**

### CODE REVIEW

**Comment by metlos** [comment]
test comment

**Comment by rhq-migration-test-user** [comment]
Closing just for fun

**Comment by rhq-migration-test-user** [comment]
Closing just for fun 2

**Comment by rhq-migration-test-user** [comment]
Closing just for fun 3

**Comment by rhq-migration-test-user** [comment]
Closing just for fun 3

**Comment by rhq-migration-test-user** [comment]
Closing just for fun 3

**Comment by rhq-migration-test-user** [comment]
Closing just for fun 3

**Comment by rhq-migration-test-user** [comment]
Closing just for fun 3

**Comment by rhq-migration-test-user** [comment]
Closing just for fun 3

**Comment by rhq-migration-test-user** [comment]
Closing just for fun 3

**Comment by rhq-migration-test-user** [comment]
Closing just for fun 3

**Comment by rhq-migration-test-user** [comment]
Closing just for fun 3

**Comment by rhq-migration-test-user** [comment]
Closing just for fun 2

**Comment by rhq-migration-test-user** [comment]
Closing just for fun 2

**Comment by rhq-migration-test-user** [comment]
Closing just for fun, yay

**Pull request merged**
